version: '3.1'
services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        depends_on:
            - api
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
        ports:
            - 80:80
    api:
        build:
            context: ./
            dockerfile: Dockerfile
        # image: flask:0.0.1
        # container_name: flask
        # volumes:
        #     - ./:/code/
        # environment:
        #     - FLASK_APP=/code/main.py
        # command: flask run --host=0.0.0.0
        networks:
            my-network:
                aliases:
                    - python-app
        ports:
            - 5000:5000

networks:
    my-network: