name: DEVELOPMENT node service Deployment
on: 
  push:
    tags:
      - bmi-svc.v1.*

jobs:
  test_service:
    name: build and test service image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: test pre-deploy
        run: docker-compose -f docker-compose-test-service.yml -p ci up --abort-on-container-exit --exit-code-from sut 

  push_to_registry:
    needs: test_service
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # - name: create dockerfile
      #   run: cp dockerfiles/bmi_service/Dockerfile.bmi_service Dockerfile
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}       

      - name: remove old docker instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.SSH_USER }}
          # port: ${{ secrets.TEST_PORT }}
          key: ${{ secrets.DEV_PRIV_KEY }}
          script: |
            docker stop ${{ secrets.DOCKER_IMAGE }}
            docker rm ${{ secrets.DOCKER_IMAGE }} 
            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: install new docker instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.SSH_USER }}
          # port: ${{ secrets.TEST_PORT }}
          key: ${{ secrets.DEV_PRIV_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
            docker run -d --name "${{ secrets.DOCKER_IMAGE }}" -p 3000:3000 -it ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: after-deploy test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.SSH_USER }}
          # port: ${{ secrets.TEST_PORT }}
          key: ${{ secrets.DEV_PRIV_KEY }}
          script: |
            curl "localhost:3000/?height=180&weight=80"
